spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: paldeepsekhon
    password: 3222
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
